### ISSUE TITLE
Private file info rather than view on IPFS

### ISSUE THREAD

**Issue by bmann** [webnative-examples/webnative-app-template#51]
Remove the "view on IPFS" link for private files / photos. 

Maybe an "I" for info button with a short note "private files can only be viewed on other devices. Follow private file sharing (link to GitHub issue here)"

**Comment by avivash** [comment]
@depatchedmode flagging this for the design team as there may be some specific design considerations we want to implement to show users that this is a feature/benefit of WNFS. Otherwise, i can implement a simple tooltip, as suggested in the issue description 👍🏼

**Comment by depatchedmode** [comment]
I'm actually tempted to leave the "view on IPFS" link in there, with a supporting explanation. I think it's more instructional in the sense that it provides evidence of the fact your data is encrypted. Because this sample Photos gallery in the WAT is meant to be a learning resource for developers, I think we should just be explicit and up front.

Something like this:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/84613835/202819675-521928bf-ae7d-4e79-ad91-3d1850e517fd.png">

**Comment by avivash** [comment]
> I'm actually tempted to leave the "view on IPFS" link in there, with a supporting explanation. I think it's more instructional in the sense that it provides evidence of the fact your data is encrypted. Because this sample Photos gallery in the WAT is meant to be a learning resource for developers, I think we should just be explicit and up front.
> 
> Something like this: <img alt="image" width="844" src="https://user-images.githubusercontent.com/84613835/202819675-521928bf-ae7d-4e79-ad91-3d1850e517fd.png">

Nice! I like that idea 👍🏼

**Comment by avivash** [comment]
This has been implemented in the WalletAuth repos, as well
