### ISSUE TITLE
Deploys are broken to Netlify and Cloudflare

### ISSUE THREAD

**Issue by jessmartin** [webnative-examples/webnative-app-template#88]
Deployed demo links from the README are broken for Netlify (stopped deploying) and Cloudflare (got deleted).
It's a permissions/accounts thing. I was trying to do the right thing with a company-level account instead of doing the quick-and-dirty with a personal account and they are making it hard to do the right thing.

**Comment by avivash** [comment]
@therealjeffg cloudflare/netlify deployments for updates to `main` and all PRs are now working. You'll notice in the screenshot below that `walletauth` has a different domain, that's because someone else apparently got the domain before us 😅 https://walletauth.pages.dev/

<img width="856" alt="image" src="https://user-images.githubusercontent.com/1179291/202028486-fdba6d9b-0b66-461d-abde-06fbf5b1123d.png">

**Comment by therealjeffg** [comment]
Awesome!
